from fastapi import FastAPI, UploadFile, File, HTTPException, Header
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from typing import List, Optional
from dotenv import load_dotenv
import os

from database import init_db, SessionLocal
from models import ContradictionRecord
from pydantic import BaseModel

class StatusUpdateRequest(BaseModel):
    contradiction_id: str
    status: str

init_db()

from services.ai_analyzer import analyze_documents

load_dotenv()

app = FastAPI(title="JurisSync API", description="API for Contradictory Legal Document Detection")

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:3001", "http://127.0.0.1:3000", "http://127.0.0.1:3001"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Ensure public directory exists
os.makedirs("public", exist_ok=True)
# Mount static files
app.mount("/public", StaticFiles(directory="public"), name="public")

@app.post("/api/analyze-bundle")
async def analyze_bundle(
    files: List[UploadFile] = File(...),
    x_user_role: Optional[str] = Header(None)
):
    print(f"DEBUG: Received x_user_role = {x_user_role}")
    if not files:
        raise HTTPException(status_code=400, detail="No files provided")
    
    # Analyze the bundle using the ai_analyzer service
    try:
        result = await analyze_documents(files, role=x_user_role)
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
class SearchRequest(BaseModel):
    query: str

class InsightRequest(BaseModel):
    contradiction_id: str
    case_title: str
    insight_notes: str

@app.post("/api/update-contradiction-status")
async def update_contradiction_status(request: StatusUpdateRequest, x_user_role: Optional[str] = Header(None)):
    if x_user_role not in ['judge', 'lawyer', 'org_admin', 'AUTHORIZED']:
        raise HTTPException(status_code=403, detail="Insufficient clearance to verify or dismiss.")
    
    # If this is a mock contradiction generated by the fallback (IDs start with c-), just return success
    if str(request.contradiction_id).startswith("c-"):
        return {"message": "Status updated successfully (Mock)", "status": request.status}
    
    db = SessionLocal()
    try:
        record = db.query(ContradictionRecord).filter(ContradictionRecord.id == request.contradiction_id).first()
        if not record:
            raise HTTPException(status_code=404, detail="Contradiction not found")
        record.status = request.status
        db.commit()
        return {"message": "Status updated successfully", "status": record.status}
    except HTTPException:
        db.rollback()
        raise
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        db.close()

@app.get("/api/timeline-analysis")
async def timeline_analysis(contradiction_id: str, x_user_role: Optional[str] = Header(None)):
    if x_user_role not in ['judge', 'lawyer', 'org_admin', 'AUTHORIZED']:
        raise HTTPException(status_code=403, detail="Insufficient clearance for deep analysis.")
    
    # Dynamic chronological timeline generation based on the anomaly
    if contradiction_id == "c-1":
        return {
            "timeline": [
                {
                    "date": "Jan 2023",
                    "event": "Tenant signs lease agreement declaring exclusive residential occupation at Indiranagar, Bengaluru.",
                    "source": "Document A",
                    "conflict_flag": False
                },
                {
                    "date": "Mar 2023",
                    "event": "Tenant occupies Bengaluru residence full-time.",
                    "source": "Document A",
                    "conflict_flag": False
                },
                {
                    "date": "Aug 2023",
                    "event": "Tenant accepts offer for full-time on-site executive duties at Corporate HQ in Nariman Point, Mumbai.",
                    "source": "Document B",
                    "conflict_flag": True
                },
                {
                    "date": "Sep 2023",
                    "event": "Employment commences in Mumbai without remote work approval, conflicting with Bengaluru lease terms.",
                    "source": "Document B",
                    "conflict_flag": True
                }
            ],
            "pattern_detected": "Geographical impossibility: Concurrent full-time physical presence required in two distinct cities (Bengaluru and Mumbai) separated by ~980km."
        }
    elif contradiction_id == "c-2":
        return {
            "timeline": [
                {
                    "date": "Nov 15, 2023",
                    "event": "Initial filing alleges unauthorized transfer of ₹1,85,00,000.00 to offshore account.",
                    "source": "Document B",
                    "conflict_flag": False
                },
                {
                    "date": "Dec 02, 2023",
                    "event": "Defendant files response brief.",
                    "source": "Document A",
                    "conflict_flag": False
                },
                {
                    "date": "Dec 05, 2023",
                    "event": "Response brief attacks plaintiff's 'notoriously poor moral character' instead of addressing financial transfer.",
                    "source": "Document A",
                    "conflict_flag": True
                }
            ],
            "pattern_detected": "Ad Hominem Fallacy: Deflection from substantive financial allegations (₹1.85Cr transfer) to personal character attacks."
        }
    else:
        # Fallback for dynamic/real LLM generated contradictions
        return {
            "timeline": [
                {
                    "date": "Initial Filing",
                    "event": "Document A submitted to record.",
                    "source": "Doc A",
                    "conflict_flag": False
                },
                {
                    "date": "Subsequent Filing",
                    "event": "Document B submitted, introducing a contradictory claim or logical fallacy.",
                    "source": "Doc B",
                    "conflict_flag": True
                }
            ],
            "pattern_detected": "Temporal/Logical anomaly detected between submitted documents."
        }

@app.post("/api/legal-search")
async def legal_search(request: SearchRequest, x_user_role: Optional[str] = Header(None)):
    if x_user_role not in ['judge', 'lawyer', 'org_admin', 'AUTHORIZED']:
        raise HTTPException(status_code=403, detail="Insufficient clearance.")
    
    # Mocking a rich legal search response tailored to our specific test case
    return {
        "results": [
            {
                "id": "prec-101",
                "case_title": "State of Maharashtra v. Reliance Industries Ltd. (2018)",
                "court": "Supreme Court of India",
                "year": 2018,
                "relevance": 98.5,
                "summary": "The Supreme Court ruled that conflicting geographical affidavits signed under penalty of perjury constitute prima facie evidence of intent to defraud, bypassing standard evidentiary protections under the Indian Evidence Act."
            },
            {
                "id": "prec-102",
                "case_title": "Desai v. Commissioner of Income Tax (2021)",
                "court": "Delhi High Court",
                "year": 2021,
                "relevance": 92.0,
                "summary": "Held that employment agreements stipulating full-time on-site work supersede generalized affidavits of residence when determining physical jurisdiction for taxation under DPDP compliance."
            }
        ]
    }

@app.post("/api/save-insight")
async def save_insight(request: InsightRequest, x_user_role: Optional[str] = Header(None)):
    if x_user_role not in ['judge', 'lawyer', 'org_admin', 'AUTHORIZED']:
        raise HTTPException(status_code=403, detail="Insufficient clearance.")
    # In a real scenario, this would save to a database table related to the case/contradiction
    return {"status": "success", "message": f"Insight from {request.case_title} saved to dossier."}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
